[package]
name = "flatgeobuf"
version = "0.3.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"
description = "FlatGeobuf for Rust."
homepage = "https://bjornharrtell.github.io/flatgeobuf/"
repository = "https://github.com/bjornharrtell/flatgeobuf"
readme = "README.md"
license = "ISC"
license-file = "../../LICENSE"
keywords = ["geo", "r-tree"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "0.6"
byteorder = "1.3"

[dev-dependencies]
rand = "0.7"
